### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TheOtterlord** [TheOtterlord/opinion-otter#1]
- [ ] Sign up process
  - [ ] Require invite (this is intended to be self-hosted)
  - [ ] Guide through project creation
- [ ] Switch back to using project ids to support multiple projects
- [ ] Setup docs
  - [ ] Deploy to Netlify
  - [ ] Add the feedback widget to the docs themselves using the integration

<sub>Subject to change</sub>
